// packages/solid/src/views/people/PersonDetail.view.tsx
import personDetailStyles from '@friendly-ui/design/person_detail.module.css';
import { Navigate, useParams } from 'solid-app-router';
import { autoAnimate } from 'solid-auto-animate';
import { Component, JSX, Match, Switch } from 'solid-js';
import { useFriendsStore } from '_shared/friendsStore';
import PageTitle from '_shared/PageTitle';
import { PersonId, RequestStatus } from '_shared/types';
import { usePeopleRouteData } from './primitives';

interface AddBtnProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  status: RequestStatus;
}

const AddBtn: Component<AddBtnProps> = (p) => {
  return (
    <button
      class={personDetailStyles.addBtn}
      type="button"
      data-status={p.status}
      tabIndex={p.status === 'requested' ? -1 : undefined}
      aria-disabled={p.status === 'requested'}
      onClick={p.onClick}
    >
      <Switch fallback="Add Friend">
        <Match when={p.status === 'requested'}>Pending</Match>
        <Match when={p.status === 'accepted'}>Unfriend</Match>
      </Switch>
    </button>
  );
};

const PersonDetailView: Component = () => {
  const params = useParams();
  const routeData = usePeopleRouteData();
  const [friends, methods] = useFriendsStore();
  autoAnimate; // to prevent TS from removing the directive

  function friendStatus(personId: PersonId) {
    return friends.statusMap[personId];
  }

  function handleAddFriend(id: PersonId, event: MouseEvent) {
    const status = friendStatus(id);

    if (status === 'requested') {
      event.preventDefault();
      return;
    }

    if (status === 'accepted') {
      methods.removeFriend(id);
      return;
    }

    methods.addFriend(id);
  }

  function renderPerson() {
    const fetchedPeople = routeData();

    if (fetchedPeople.length === 0) {
      return null;
    }

    const person = fetchedPeople.find((person) => person.id === params.id);

    if (!person) {
      return <Navigate href="/people" />;
    }

    const { id, name, description, imageUrl } = person;

    return (
      <>
        <PageTitle>{name}</PageTitle>
        <div>
          <img src={imageUrl} alt="" class={personDetailStyles.avatar} />
        </div>
        <div class={personDetailStyles.bio} use:autoAnimate>
          <h2 class={personDetailStyles.name}>{name}</h2>
          <p class={personDetailStyles.description}>{description}</p>
          <AddBtn status={friendStatus(id)} onClick={[handleAddFriend, id]} />
        </div>
      </>
    );
  }

  return (
    <div
      class={personDetailStyles.wrapper}
      use:autoAnimate={{
        duration: 200,
      }}
    >
      {renderPerson()}
    </div>
  );
};

export default PersonDetailView;

// packages/react/src/views/people/PersonDetail.view.tsx
import personDetailStyles from '@friendly-ui/design/person_detail.module.css';
import { useMatch } from '@tanstack/react-location';
import { ButtonHTMLAttributes, FC } from 'react';
import { useFriendsStore } from '_shared/friendsStore';
import { RequestStatus } from '_shared/types';

interface AddBtnProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  status: RequestStatus;
}

const AddBtn: FC<AddBtnProps> = ({ status, onClick }) => {
  function renderContent() {
    if (status === 'requested') {
      return 'Pending';
    }

    if (status === 'accepted') {
      return 'Unfriend';
    }

    return 'Add Friend';
  }

  return (
    <button
      className={personDetailStyles.addBtn}
      type="button"
      data-status={status}
      tabIndex={status === 'requested' ? -1 : undefined}
      aria-disabled={status === 'requested'}
      onClick={onClick}
    >
      {renderContent()}
    </button>
  );
};

function PersonDetailView() {
  const {
    params: { id },
    data: { people },
  } = useMatch();
  const { statusMap, addFriend, removeFriend } = useFriendsStore();

  const friendStatus = statusMap[id];
  const person = people.find((person) => person.id === id);
  const { name, description, imageUrl } = person;

  function handleClick(event) {
    if (friendStatus === 'requested') {
      event.preventDefault();
    }

    if (friendStatus === 'accepted') {
      removeFriend(id);
      return;
    }

    addFriend(id);
  }

  return (
    <div className={personDetailStyles.wrapper}>
      <div>
        <img src={imageUrl} alt="" className={personDetailStyles.avatar} />
      </div>
      <div className={personDetailStyles.bio}>
        <h2 className={personDetailStyles.name}>{name}</h2>
        <p className={personDetailStyles.description}>{description}</p>
        <AddBtn status={friendStatus} onClick={handleClick} />
      </div>
    </div>
  );
}

export default PersonDetailView;
