// packages/react/src/views/root/Root.shell.tsx
import layoutStyles from '@friendly-ui/design/layout.module.css';
import { Outlet } from '@tanstack/react-location';
// import Search from './Search';

const RootShell = () => {
  return (
    <div className={layoutStyles.layoutApp}>
      {/* <Search /> */}
      {/* <Suspense fallback="loading"> */}
      <Outlet />
      {/* </Suspense> */}
    </div>
  );
};

export default RootShell;

// packages/solid/src/views/root/Root.shell.tsx
import { Component, Suspense } from 'solid-js';
import { Outlet } from 'solid-app-router';
import Search from './Search';
import layoutStyles from '@friendly-ui/design/layout.module.css';

const RootShell: Component = () => {
  return (
    <div class={layoutStyles.layoutApp}>
      <Search />
      <Suspense fallback="loading">
        <Outlet />
      </Suspense>
    </div>
  );
};

export default RootShell;
