// packages/solid/src/shared/PageTitle.tsx
import { Component, ComponentProps } from 'solid-js';
import { Title } from 'solid-meta';

export type PageTitleProps = ComponentProps<typeof Title>;

const PageTitle: Component<PageTitleProps> = (p) => {
  function getContent() {
    const baseContent = 'Friendly Solid';
    const { children } = p;

    if (children) {
      return `${children} | ${baseContent}`;
    }

    return baseContent;
  }

  return <Title children={getContent()} />;
};

export default PageTitle;

// packages/react/src/shared/PageTitle.tsx
import { FC } from 'react';
import { Title } from 'react-head';

export interface PageTitleProps {
  children: string;
}

const PageTitle: FC<PageTitleProps> = (p) => {
  const { children } = p;
  function getContent() {
    const baseContent = 'Friendly React';

    if (children) {
      return `${children} | ${baseContent}`;
    }

    return baseContent;
  }

  return <Title>{getContent()}</Title>;
};

export default PageTitle;
