// packages/react/src/shared/searchStore.tsx
import { ReactNode } from 'react';
import create from 'zustand';
import createContext from 'zustand/context';
import { immer } from 'zustand/middleware/immer';
import { SearchStore, SearchState } from './types';

const { Provider, useStore } = createContext<SearchStore>();

const createStore = () =>
  create<SearchState>()(
    immer((set) => ({
      query: '',
      history: [],
      runSearch(query) {
        set((draft) => {
          const lastQuery = draft.query;

          draft.query = query;

          if (lastQuery) {
            draft.history.splice(0, 0, lastQuery);
          }
        });
      },
      clearSearch() {
        this.runSearch('');
      },
    })),
  );

export const SearchStoreProvider = (props: { children: ReactNode }) => {
  return <Provider createStore={createStore} {...props} />;
};

export { useStore as useSearchStore };

// packages/solid/src/shared/searchStore.tsx
import { createContext, ParentComponent, useContext } from 'solid-js';
import { createStore, produce } from 'solid-js/store';
import { SearchMethods, SearchState, SearchStore } from './types';

const storeContext = createContext<SearchStore>();

export function useSearchStore() {
  const store = useContext(storeContext);

  if (!store) {
    throw new Error('Please use it inside SearchStoreProvider component');
  }

  return store;
}

const initialState: SearchState = {
  query: '',
  history: [],
};

export const SearchStoreProvider: ParentComponent = (p) => {
  const [search, setSearch] = createStore(initialState);

  const methods: SearchMethods = {
    runSearch(query) {
      setSearch(
        produce((draft) => {
          const lastQuery = draft.query;

          draft.query = query;

          if (lastQuery) {
            draft.history.splice(0, 0, lastQuery);
          }
        }),
      );
    },
    clearSearch() {
      methods.runSearch('');
    },
  };

  const store: SearchStore = [search, methods];

  return <storeContext.Provider value={store} children={p.children} />;
};
