// packages/solid/src/views/Home.view.tsx
import homeStyles from '@friendly-ui/design/home.module.css';
import { Link } from 'solid-app-router';
import { Component } from 'solid-js';
import PageTitle from '_shared/PageTitle';

const Home: Component = () => {
  return (
    <div class={homeStyles.wrapper}>
      <PageTitle>Home</PageTitle>
      <Link class={homeStyles.demoLink} href="/people">
        Solid Demo
      </Link>
      <Link
        class={homeStyles.demoLink}
        href="https://friendly-ui-react.vercel.app/people"
      >
        React Demo
      </Link>
    </div>
  );
};

export default Home;

// packages/react/src/views/Home.view.tsx
import homeStyles from '@friendly-ui/design/home.module.css';
import { Link } from '@tanstack/react-location';
import PageTitle from '_shared/PageTitle';

function HomeView() {
  return (
    <div className={homeStyles.wrapper}>
      <PageTitle>Home</PageTitle>
      <Link className={homeStyles.demoLink} to="/people">
        React Demo
      </Link>
      <a
        className={homeStyles.demoLink}
        href="https://friendly-ui-solid.vercel.app/people"
      >
        Solid Demo
      </a>
    </div>
  );
}

export default HomeView;
