// packages/solid/src/views/root/Search.tsx
import { Component, createSignal, Show, JSX, For } from 'solid-js';
import { useSearchStore } from '_shared/searchStore';
import { SearchHistoryIcon, ClearSearchIcon } from '_shared/Icons';
import searchStyles from '@friendly-ui/design/search.module.css';
import { autoAnimate } from 'solid-auto-animate';

type SubmitHandler = JSX.EventHandlerUnion<HTMLFormElement, SubmitEvent>;

const Search: Component = () => {
  const [search, methods] = useSearchStore();
  const [show, setShow] = createSignal(false);
  autoAnimate; // to prevent TS from removing the directive

  const handleSubmit: SubmitHandler = (event) => {
    event.preventDefault();
    const formElem = event.currentTarget;
    const formData = new FormData(formElem);
    const query = formData.get('search');

    if (typeof query === 'string') {
      methods.runSearch(query);
    }
  };

  const handleReset = () => {
    methods.clearSearch();
  };

  return (
    <section use:autoAnimate>
      <form
        class={searchStyles.searchForm}
        autocomplete="off"
        onSubmit={handleSubmit}
        onReset={handleReset}
      >
        <input
          class={searchStyles.searchField}
          type="text"
          placeholder="Search"
          name="search"
          aria-label="Search"
        />
        <button
          class={searchStyles.historyBtn}
          type="button"
          onClick={() => setShow((old) => !old)}
        >
          <SearchHistoryIcon />
        </button>
        <button class={searchStyles.resetBtn} type="reset">
          <ClearSearchIcon />
        </button>
      </form>
      <Show when={show()}>
        <ul class={searchStyles.history}>
          <For each={search.history} fallback={<li>No Search History</li>}>
            {(searchRecord) => <li class={searchStyles.historyItem}>{searchRecord}</li>}
          </For>
        </ul>
      </Show>
    </section>
  );
};

export default Search;

// packages/react/src/views/root/Search.tsx
import searchStyles from '@friendly-ui/design/search.module.css';
import { FormEventHandler, useState } from 'react';
import { ClearSearchIcon, SearchHistoryIcon } from '_shared/Icons';
import { useSearchStore } from '_shared/searchStore';

type SubmitHandler = FormEventHandler<HTMLFormElement>;

const Search = () => {
  const { history, runSearch } = useSearchStore();
  const [show, setShow] = useState(false);

  const handleSubmit: SubmitHandler = (event) => {
    event.preventDefault();
    const formElem = event.currentTarget;
    const formData = new FormData(formElem);
    const query = formData.get('search');

    if (typeof query === 'string') {
      runSearch(query);
    }
  };

  const handleReset = () => {
    runSearch('');
  };

  const historyList = history.length === 0 ? ['No Search History'] : history;

  return (
    <section>
      <form
        className={searchStyles.searchForm}
        autoComplete="off"
        onSubmit={handleSubmit}
        onReset={handleReset}
      >
        <input
          className={searchStyles.searchField}
          type="text"
          placeholder="Search"
          name="search"
          aria-label="Search"
        />
        <button
          className={searchStyles.historyBtn}
          type="button"
          onClick={() => setShow((old) => !old)}
        >
          <SearchHistoryIcon />
        </button>
        <button className={searchStyles.resetBtn} type="reset">
          <ClearSearchIcon />
        </button>
      </form>
      {show && (
        <ul className={searchStyles.history}>
          {historyList.map((searchRecord) => (
            <li className={searchStyles.historyItem} key={searchRecord}>
              {searchRecord}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
};

export default Search;
